# Generated by Django 3.2.7 on 2021-10-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content2',
            field=models.TextField(blank=True),
        ),
    ]
