# Generated by Django 3.0.4 on 2021-11-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='region',
            field=models.ManyToManyField(to='advertisement.AdvertisementRegion', verbose_name='Регион'),
        ),
    ]
